environment:
  matrix:
  - TARGET: x86_64-pc-windows-msvc
  - TARGET: i686-pc-windows-msvc
  - TARGET: i686-pc-windows-gnu
install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-1.5.0-${env:TARGET}.exe"
  - rust-1.5.0-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - SET PATH=%PATH%;C:\MinGW\bin
  - rustc -V
  - cargo -V
  - ps: Start-FileDownload 'https://cdn.rawgit.com/tedsta/getting-started-with-piston/2e908548c5538cfb8c1d1b1b2d56dfe794e60a6e/windows_clibs/i686/libfreetype-6.a'
  - cmd: move libfreetype-6.a "C:\Program Files (x86)\Rust\bin\rustlib\${env:TARGET}\lib\"

build: false

test_script:
  - cargo build -v